# Generated by Django 4.1 on 2025-04-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="product",
            name="urlpath",
            field=models.CharField(default="", max_length=2048),
            preserve_default=False,
        ),
    ]
