# Generated by Django 4.1 on 2025-04-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_telegramuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="last_login_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
